version: "3"
services:
  app:
    container_name: appname-app
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile 
    tty: true
    command: /bin/bash
    volumes:
      - .:/go/src/app
  